
from src.elmt.Club import Club
def getClubIds():
    return (x.id for x in getClubs())
    
def getClubNames():
    return (x.name for x in getClubs())

def getClubByid(clubId):
    return next((x for x in getClubs() if x.id == clubId), None)

def getClubs():
    return [
        Club("ACC_1.FR.0309", "LAT Sense (Lauf und Athletikteam)"),
        Club("ACC_1.FR.0310", "Rechthalten Athletic Team"),
        Club("ACC_1.FR.0311", "TSV Heitenried"),
        Club("ACC_1.FR.0312", "TV Alterswil"),
        Club("ACC_1.FR.0319", "TV BÃ¶singen"),
        Club("ACC_1.FR.0320", "TV WÃ¼nnewil"),
        Club("ACC_1.FR.0321", "TSV DÃ¼dingen"), 
        Club("ACC_1.FR.0323", "AC Murten"),
        Club("ACC_1.FR.0324", "TV Murten"),                
        Club("ACC_1.FR.0325", "TV Plaffeien"),
        Club("ACC_1.FR.0329", "TSV Kerzers"),
        Club("ACC_1.FR.0335", "TSV St. Antoni"),
        Club("ACC_1.VS.1720", "STV Gampel"),
        Club("ACC_1.VS.1719", "LV Visp"),
        Club("ACC_1.VS.1716", "LLT Oberwallis"),
        Club("ACC_1.VS.1717", "TV Naters"),
        Club("ACC_1.VS.1716", "LLT Oberwallis"),
        Club("ACC_1.SO.1202", "Biberist aktiv! Leichtathletik"),
        Club("ACC_1.SO.1201", "TV Grenchen"),
        Club("ACC_1.SO.1203", "STV Bettlach"),
        Club("ACC_1.SO.1204", "STV Selzach"),
        Club('ACC_1.BE.0103', 'LAC Biel'),
        Club('ACC_1.BE.0105', 'STV Biel'),
        #Club('ACC_1.BE.0107', 'FSG La Neuveville'),
        #Club('ACC_1.BE.0109', 'CA Courtelary'),
        #Club('ACC_1.BE.0112', 'CA Moutier'),
        Club('ACC_1.BE.0115', 'GG Bern'),
        Club('ACC_1.BE.0116', 'STB Leichtathletik'),
        Club('ACC_1.BE.0117', 'TV LÃ¤nggasse Bern'),
        Club('ACC_1.BE.0121', 'LAG TV Zollikofen'),
        Club('ACC_1.BE.0123', 'TV Bolligen'),
        Club('ACC_1.BE.0125', 'TV Ostermundigen'),
        Club('ACC_1.BE.0128', 'TV Schwarzenburg'),
        Club('ACC_1.BE.0129', 'TV Oberwangen'),
        Club('ACC_1.BE.0130', 'TSV Frauenkappelen'),
        Club('ACC_1.BE.0132', 'LAC Wohlen'),
        Club('ACC_1.BE.0133', 'TV Lyss'),
        Club('ACC_1.BE.0136', 'TV Fraubrunnen'),
        Club('ACC_1.BE.0137', 'TV Herzogenbuchsee'),
        Club('ACC_1.BE.0138', 'LA RÃ¼egsauschachen'),
        Club('ACC_1.BE.0142', 'LC Kirchberg'),
        Club('ACC_1.BE.0144', 'TV Sumiswald'),
        Club('ACC_1.BE.0145', 'TV GrosshÃ¶chstetten'),
        Club('ACC_1.BE.0146', 'TV Konolfingen Athletics'),
        Club('ACC_1.BE.0147', 'SK Langnau'),
        Club('ACC_1.BE.0148', 'TV Trubschachen'),
        Club('ACC_1.BE.0152', 'All Blacks Thun'),
        Club('ACC_1.BE.0154', 'LV Thun'),
        Club('ACC_1.BE.0156', 'TV Spiez'),
        Club('ACC_1.BE.0157', 'LC Scharnachtal'),
        Club('ACC_1.BE.0158', 'TV Saanen-Gstaad'),
        Club('ACC_1.BE.0159', 'TV Unterseen'),
        Club('ACC_1.BE.0160', 'TV Meiringen'),
        Club('ACC_1.BE.0161', 'LV Langenthal'),
        Club('ACC_1.BE.0162', 'TV Aeschi'),
        Club('ACC_1.BE.0163', 'LV Huttwil'),
        Club('ACC_1.BE.0166', 'TV Attiswil'),
        Club('ACC_1.BE.0167', 'UOV Burgdorf - LÃ¤ufergruppe'),
        Club('ACC_1.BE.0168', 'SATUS Biel-Stadt'),
        #Club('ACC_1.BE.0168.old', 'SATUS Biel-Stadt (gelöscht im alten System)'),
        Club('ACC_1.BE.0170', 'TV Oberdiessbach'),
        Club('ACC_1.BE.0171', 'LA Bern'),
        #Club('ACC_1.BE.0173', 'perü timing'),
        Club('ACC_1.BE.0177', 'LauftrÃ¤ff BÃ¼ren an der Aare'),
        Club('ACC_1.BE.0180', 'LGRL RÃ¼egsauschachen-LÃ¼tzelflÃ¼h'),
        #Club('ACC_1.BE.0181', 'Verein Steinhölzlilauf'),
        #Club('ACC_1.BE.0182', 'Verein GurtenClassic'),
        Club('ACC_1.BE.0183', 'Fun and Run Thun'),
        Club('ACC_1.BE.0184', 'TV Aarberg Leichtathletik'),
        Club('ACC_1.BE.0185', 'Gerbersport'),
        Club('ACC_1.BE.0186', 'Bieler Lauftage'),
        Club('ACC_1.BE.0187', 'Satus Burgdorf'),
        Club('ACC_1.BE.0188', 'Biel/Bienne Athletics'),
        #Club('ACC_1.BE.0190', 'Schneesport Club Wiedlisbach'),
        #Club('ACC_1.BE.0192', 'runningtrainer.ch'),
        #Club('ACC_1.BE.0193', 'Grand-Prix von Bern'),
        #Club('ACC_1.BE.0194', 'Verein Running Grindelwald'),
        #Club('ACC_1.BE.0195', 'Jungfrau-Marathon'),
        #Club('ACC_1.BE.0197', 'Verein City-Athletics Langenthal'),
        #Club('ACC_1.BE.0198', 'Verein Langenthaler Stadtlauf'),
        #Club('ACC_1.BE.0199', 'OK Bärner Bärgloufcup'),
        #Club('ACC_1.BE.0200', 'Ingold Rönners Laufträff'),
        Club('ACC_1.BE.0201', 'TV LÃ¼tzelflÃ¼h Athletics'),
        #Club('ACC_1.BE.0202', 'FSG St-Imier'),
        Club('ACC_1.BE.0203', 'TVM Buchsi-Athletics'),
        Club('ACC_1.BE.0204', 'TSV Vechigen'),
        #Club('ACC_1.BE.0205', 'WingTsun-Running Bern'),
        #Club('ACC_1.BE.0206', 'FSG Féminine Tavannes'),
        #Club('ACC_1.BE.0207', 'Laufgruppe Willigen LGW'),
        Club('ACC_1.BE.0208', 'Turnverein Uetendorf'),
        #Club('ACC_1.BE.0210', 'CITIUS Meeting'),
        Club('ACC_1.BE.0211', 'TIP-TOP Swiss Polysport'),
        #Club('ACC_1.BE.0212', 'Association Moutier Trail'),
        Club('ACC_1.BE.0213', 'GWP Track Team'),
        Club('ACC_1.BE.0214', 'Satus Interlaken'),
        Club('ACC_1.BE.0215', 'LV Kandertal'),
        #Club('ACC_1.BE.0216', 'Vogellisi Berglauf'),
        Club('ACC_1.BE.0217', 'Turn- und Sportverein Wangen an der Aare')
        ]


if __name__ == '__main__':
    clubs = getClubs()
    print(clubs[0].name)